name: Setup boilerplate

on:
  workflow_dispatch:
    inputs:
      boilerplate:
        type: choice
        description: Name of boilerplate
        options:
        - fullstack-boilerplate-flask
        - fullstack-boilerplate-sanic-react
        - fullstack-boilerplate-flask-react
        - fullstack-boilerplate-django-react
        - fullstack-boilerplate-express-react
        - fullstack-boilerplate-typescript-express-react
        - fullstack-boilerplate-ruby-vue
        - fullstack-boilerplate-ruby-ember
        - fullstack-boilerplate-nestjs-angular
        - fullstack-boilerplate-react-nextjs
        - fullstack-boilerplate-dotnet-angular
        - fullstack-boilerplate-java-springboot-vue-typescript
        - fullstack-boilerplate-php-laravel-vue
        - fullstack-boilerplate-java-springboot-react-typescript
        - fullstack-boilerplate-java-springboot-angular
        - fullstack-boilerplate-php-react-nextjs
        required: true
      branch-name:
        type: string
        description: Name of the branch to initialize boilerplate in
        required: true
        default: implementation


jobs:
  setup-boilerplate:
    name: Setup boilerplate
    uses: DevSkillsHQ/setup-boilerplate-workflow/.github/workflows/setup-boilerplate.yml@cypress12
    permissions:
      contents: write
    with:
      boilerplate: ${{ github.event.inputs.boilerplate }}
      branch-name: ${{ github.event.inputs.branch-name }}
